### ISSUE TITLE
Socket connects but stomp doesn't

### ISSUE THREAD

**Issue by hamzabinamin** [Romixery/SwiftStomp#10]
Hello,
I am trying to connect to my ratchet web socket server. The server works on android to send and receive chat messages.

I integrated your library in iOS and while the socket connects but I see in the logs that the stomp isn't connecting. What do I need to add in order for the stomp protocol to connect? Or is there some way I can disable stomp and just use sockets for sending and receiving messages?

```
ChatEmbeddedVC onSocketEvent
2022-04-11 15:21:22 SwiftStomp [INFO]:	 Scoket: connected: ["Upgrade": "websocket", "X-Powered-By": "Ratchet/0.4.3", "Sec-WebSocket-Accept": "Ma4OIuMuHxgO2CHr8SzNBBxnW7I=", "Connection": "Upgrade"]
```

**Comment by hamzabinamin** [comment]
@Romixery can you help on this one please?

**Comment by Romixery** [comment]
Hi @hamzabinamin 
Unfortunately, I haven't any experience working with Ratchet. Please consider, Swiftstomp is not a websocket library, it uses STOMP protocol over websocket. The websocket transport layer is implemented and handled in Starscream.
I think you have to read Ratchet documents regarding headers or parameters it needs to connect.
Best of luck.
