### ISSUE TITLE
Socket connects and subscribes, but no message is received, only on App launch

### ISSUE THREAD

**Issue by StjepanMiske** [Romixery/SwiftStomp#11]
Hello,

I'm experiencing an issue. I successfully connect to the socket and on connect I call `swiftStomp.subscribe(to:......` , but after that I receive nothing even though I should. Also, on App start I can see that I receive messages but only when App starts. After those one or two messages, nothing.

**Comment by Romixery** [comment]
Hi,
What is your backend? Which message broker you are using?

**Comment by StjepanMiske** [comment]
ActiveMQ/5.16.3

**Comment by StjepanMiske** [comment]
Hi @Romixery any update on this issue?
