### ISSUE TITLE
(Privacy manifest)Conflict between SwiftStomp and Starscream

### ISSUE THREAD

**Issue by RoyLeeWc** [Romixery/SwiftStomp#21]
Swift Package Manager
SwiftStomp - Master
Starscream - v4.0.6 in use.

I witnessed that Starscream needed a Privacy Manifests response during the Privacy Manifests response regarding https://developer.apple.com/support/third-party-SDK-requirements/ . So I tried updating to the Starscream - v4.0.8 version
From SwiftStomp
package(url: "https://github.com/daltoniam/Starscream.git", .exact("4.0.6")),
I witnessed a forced adjustment to 4.0.6
I have to respond to Privacy Manifests by May on iOS
I would like you to modify the relevant dependencies at least up to 4.0.8.

**Comment by yaroslav-tormasov** [comment]
> Swift Package ManagerSwiftStomp - МастерStarscream - v4.0.6 в использовании.
> 
> Я yedem того, что Starscream нуждаlв в ответе Privacy Manifests во время ответа Privacy Manifests в отношении https://developer.apple.com/support/third-party-SDK-requirements/. Поэтому я попытался обновиться до версии Starscream - v4.0.8От SwiftStomppackage(url: "https://github.com/daltoniam/Starscream.git", .exact("4.0.6")),Яь свидетелем принудительной корректировки на 4.0.6Я должен ответить на манифесты конфиденциальности к маю на iOSЯ хотел бы, и и вы изменили соответствующие зависимости, по крайней мере, до 4.0.8.

did you find a solution?

**Comment by Romixery** [comment]
The Starscream has been removed from the project completely and now we are using the native `URLSessionWebSocketTask`. Please update to the latest version.
