### ISSUE TITLE
Delegate method not being called?

### ISSUE THREAD

**Issue by sookmunchan** [Romixery/SwiftStomp#7]
It only work within example project, i connect it with my own websocket url it work in example project but when i pod install it to my project and follow with the example project, it doesn't work at all. i even set the delegate = self. but the delegate method not being called. Is it i miss out anything?

**Comment by hatteajay1212** [comment]
@sookmunchan Hi, i have been coming across the same issue, have you got any solution for this?

**Comment by Romixery** [comment]
If the example project is working, so the library works as expected. Please update to the latest version because now it supports upstream. You can register subscribers, and receive the events through them, instead of delegates.
